name: Check Lint

on: pull_request

jobs:
  check_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.16.0]
        otp: [26]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - uses: actions/cache@v1
        id: mix-lint-cache
        with:
          path: deps
          key: ${{runner.os}}-${{matrix.otp}}-${{matrix.elixir}}-mix-${{hashFiles(format('{0}-{1}', github.workspace, '/mix.lock'))}}
      - name: Install mix dependencies
        if: steps.mix-lint-cache.outputs.cache-hit != 'true'
        run: mix deps.get
      - name: Check Lint
        run: mix credo --strict
